from os import PathLike
from .types import (DataPolicy as DataPolicy, Activity as Activity, ApHistory as ApHistory,
    IgrfResult as IgrfResult, IriResult as IriResult, HwmResult as HwmResult,
    MsisResult as MsisResult, IriEvaluation as IriEvaluation, HwmEvaluation as HwmEvaluation,
    MsisEvaluation as MsisEvaluation, IriInput, HwmInput, MsisInput,
    IriIndexEvidence, MsisIndexEvidence, IndexSample)

class GeospaceError(RuntimeError):
    code: str
    message: str

def igrf(*, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float) -> IgrfResult: ...
def iri(*, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, rz12: float, ig12: float, f107_daily: float, f107_81_day: float) -> IriResult: ...
def hwm(*, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, activity: Activity, current_ap: float | None = ...) -> HwmResult: ...
def msis(*, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, f107a: float, f107_previous_day: float, ap_daily: float | None = ..., ap_history: ApHistory | None = ...) -> MsisResult: ...

class Session:
    def __init__(self, *, home: str | PathLike[str] | None = ..., data_policy: DataPolicy = ...) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Session: ...
    def __exit__(self, type: object, value: object, traceback: object) -> None: ...
    def prepare_iri(self, *, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, rz12: float | None = ..., ig12: float | None = ..., f107_daily: float | None = ..., f107_81_day: float | None = ..., data_policy: DataPolicy | None = ...) -> PreparedIri: ...
    def evaluate_iri(self, *, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, rz12: float | None = ..., ig12: float | None = ..., f107_daily: float | None = ..., f107_81_day: float | None = ..., data_policy: DataPolicy | None = ...) -> IriEvaluation: ...
    def prepare_hwm(self, *, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, activity: Activity | None = ..., current_ap: float | None = ..., data_policy: DataPolicy | None = ...) -> PreparedHwm: ...
    def evaluate_hwm(self, *, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, activity: Activity | None = ..., current_ap: float | None = ..., data_policy: DataPolicy | None = ...) -> HwmEvaluation: ...
    def prepare_msis(self, *, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, f107a: float | None = ..., f107_previous_day: float | None = ..., ap_daily: float | None = ..., ap_history: ApHistory | None = ..., data_policy: DataPolicy | None = ...) -> PreparedMsis: ...
    def evaluate_msis(self, *, at: str, latitude_deg: float, longitude_deg: float, altitude_km: float, f107a: float | None = ..., f107_previous_day: float | None = ..., ap_daily: float | None = ..., ap_history: ApHistory | None = ..., data_policy: DataPolicy | None = ...) -> MsisEvaluation: ...

class PreparedIri:
    @property
    def input(self) -> IriInput: ...
    @property
    def indices(self) -> IriIndexEvidence: ...
    def evaluate(self) -> IriEvaluation: ...
    def with_overrides(self, *, rz12: float | None = ..., ig12: float | None = ..., f107_daily: float | None = ..., f107_81_day: float | None = ...) -> PreparedIri: ...

class PreparedHwm:
    @property
    def input(self) -> HwmInput: ...
    @property
    def ap_index(self) -> IndexSample | None: ...
    def evaluate(self) -> HwmEvaluation: ...
    def with_activity(self, *, activity: Activity, current_ap: float | None = ...) -> PreparedHwm: ...

class PreparedMsis:
    @property
    def input(self) -> MsisInput: ...
    @property
    def indices(self) -> MsisIndexEvidence: ...
    def evaluate(self) -> MsisEvaluation: ...
    def with_overrides(self, *, f107a: float | None = ..., f107_previous_day: float | None = ..., ap_daily: float | None = ..., ap_history: ApHistory | None = ...) -> PreparedMsis: ...

def capabilities() -> list[str]: ...
class TracingGuard:
    def close(self) -> None: ...
    def __enter__(self) -> TracingGuard: ...
    def __exit__(self, type: object, value: object, traceback: object) -> None: ...
def init_tracing() -> TracingGuard: ...
