// @generated by scripts/update-cache.py; do not edit manually.

pub(crate) const SNAPSHOT_AT_UTC_MS: i64 = 1_784_215_069_897;

pub(crate) const GFZ_SHA256: &str =
    "a74cd1096e7b7711690ffba819ddf7149bf32f07a787092510407e5aa1742029";
pub(crate) const GFZ_START_YEAR: u16 = 1932;
pub(crate) const GFZ_END_YEAR: u16 = 2025;

pub(crate) const IRI_IG_RZ_SHA256: &str =
    "48e6ac1a501c39ad9842fcf75d63a86303e09852406ee4153275d4b82f9e8804";
pub(crate) const IRI_IG_RZ_START_YEAR: u16 = 1958;
pub(crate) const IRI_IG_RZ_END_YEAR: u16 = 2026;

pub(crate) const IRI_APF107_SHA256: &str =
    "25bb20ff10c9cc9bf3ec9b80774e856119145d0ce5bbf65dfd3f2bd046ef9262";
pub(crate) const IRI_APF107_START_YEAR: u16 = 1958;
pub(crate) const IRI_APF107_END_YEAR: u16 = 2024;
